apiVersion: v1
kind: Secret
metadata:
 name: postgres-secret
 namespace: ogx
type: Opaque
stringData:
 password: "redhat123"
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: postgres-ogx
 namespace: ogx
 labels:
   app: postgres-ogx
spec:
 replicas: 1
 selector:
   matchLabels:
     app: postgres-ogx
 template:
   metadata:
     labels:
       app: postgres-ogx
   spec:
     containers:
       - name: postgresql
         image: registry.redhat.io/rhel9/postgresql-15:latest
         ports:
           - containerPort: 5432
             name: postgres
         env:
           - name: POSTGRESQL_USER
             value: ogx
           - name: POSTGRESQL_DATABASE
             value: ogx
           - name: POSTGRESQL_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: postgres-secret
                 key: password
         volumeMounts:
           - name: postgres-data
             mountPath: /var/lib/pgsql/data
         securityContext:
           allowPrivilegeEscalation: false
           capabilities:
             drop:
               - ALL
           runAsNonRoot: true
           seccompProfile:
             type: RuntimeDefault
     volumes:
       - name: postgres-data
         persistentVolumeClaim:
           claimName: postgres-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: postgres-pvc
 namespace: ogx
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 15Gi
---
apiVersion: v1
kind: Service
metadata:
 name: postgres-service
 namespace: ogx
spec:
 selector:
   app: postgres-ogx
 ports:
   - protocol: TCP
     port: 5432
     targetPort: 5432