kind: ConfigMap
apiVersion: v1
metadata:
  name: llamastack
  namespace: redhat-ods-applications
  labels:
    opendatahub.io/connection-type: 'true'
    opendatahub.io/dashboard: 'true'
  annotations:
    openshift.io/display-name: LlamaStackConnectionType
    openshift.io/description: 'Connection type for Llama Stack client endpoints.'
data:
  category: '["llamastack"]'
  enabled: 'true'
  fields: '[{"type":"text","name":"LLAMA_STACK_CLIENT_BASE_URL","envVar":"LLAMA_STACK_CLIENT_BASE_URL","properties":{}}]'
